name: Increment PWA Version

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Increment version
        run: |
          CURRENT_VERSION=$(awk -F"'" '/const VERSION/ {print $2}' sw.js)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          sed -i "s/const VERSION = '$CURRENT_VERSION'/const VERSION = '$NEW_VERSION'/" sw.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sw.js
          git commit -m "Automated version bump"
          git push
