name: Increment PWA Version

on:
  push:
    branches:
      - master # Or your default branch

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        run: |
          # Extract the current version number using awk
          CURRENT_VERSION=$(awk -F"'" '/const VERSION/ {print $2}' sw.js)
          # Increment the version number
          NEW_VERSION=$((CURRENT_VERSION + 1))
          # Replace the old version with the new version in sw.js
          sed -i "s/const VERSION = '$CURRENT_VERSION'/const VERSION = '$NEW_VERSION'/" sw.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sw.js
          git commit -m "Automated version bump"
          git push
