name: Increment PWA Version

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Fetches all history so you can push back to the repository
          fetch-depth: 0
          # This token is provided by Actions, you do not need to create your own
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        run: |
          # Use sed to find the line with "const VERSION" and increment the number
          sed -i -E "s/(const VERSION = ')_([0-9]+)_(';)/\1$((\2+1))\3/" sw.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sw.js
          git commit -m "Automated version bump"
          git push
